### ISSUE TITLE
Issue in upload_bluerov2_lauch

### ISSUE THREAD

**Issue by Irrelev4nt13** [CentraleNantesROV/bluerov2#1]
Hello,

I'm using ubuntu 20.04 and ros-humble from source.

I installed your package and it's requirements. 

As you can see below I'm able to open gazebo from the `world_launch.py` but when try executing the other launch file it stops because of some xacro file.
![image](https://github.com/CentraleNantesROV/bluerov2/assets/68859596/5b311ab5-ac41-49c3-9142-dac99f71e09b)

Any suggestions would be greatly appreciated. 

PS. We talked in robot exchange and you told me to move to ROS 2 so here I am :p

**Comment by oKermorgant** [comment]
Hi,

Thanks for using this package. You need to install [`xacro`](https://github.com/ros/xacro/tree/ros2).
It is a tool allowing macros in XML and is often used in URDF files.

It is usually installed by default but as you use ROS 2 from source it was not. I'll add it as an explicit dependency.

**Comment by Irrelev4nt13** [comment]
Thank you very much for your help and your work, everything worked perfect. I would like to know if there is a way to add the heavy configuration model.

**Comment by oKermorgant** [comment]
Hi,

You can have a look at the URDF's (namely bluerov2.xacro, hydrodynamics.xacro and thrusters.xacro) and create new versions of them from the heavy configuration datasheet. 
Actually I' d be glad if you could do a pull request on this point when it works, other people may be interested in having the heavy configuration.

**Comment by Irrelev4nt13** [comment]
Sure, I will make one when it's ready, thanks again. 
Have a nice day.
