### ISSUE TITLE
ros2 launch bluerov2_description world_launch.py error

### ISSUE THREAD

**Issue by ZHANG-zzt** [CentraleNantesROV/bluerov2#3]
Hello, I entered the following command, the following error
My ros2 humble + gazebo 11

ros2 launch bluerov2_description world_launch.py
[INFO] [launch]: All log files can be found below /home/zhiteng/.ros/log/2024-04-10-11-49-08-883876-ZZT-OMEN-108714
[INFO] [launch]: Default logging verbosity is set to INFO
[ERROR] [launch]: Caught exception in launch (see debug for traceback): Caught exception when trying to load file of format [py]: SimpleLauncher.gz_launch() takes from 1 to 2 positional arguments but 3 were given

**Comment by oKermorgant** [comment]
Hi,

Thanks for this feedback. The `simple_launch` error comes from the fact that I have used the upstream version (https://github.com/oKermorgant/simple_launch) that modifies the `gz_launch` function. 
This version is pending to be released, in the meantime you should use `simple_launch` from source.

Other than that, this package is meant for Gazebo Sim and not classic (e.g. Gazebo 11). The plugins will not work on classic.

**Comment by ZHANG-zzt** [comment]
Thank you for your reply. So even with gazebo sim, it won't work for a while because of the simple_launch file？

**Comment by oKermorgant** [comment]
If you use the source until the new version is released it will be fine.
